import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: {
    default: 'Home page | Roam the Globe',
    template: '%s | Roam the Globe',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/travelBundle">Travel bundle</Link>
            <Link href="/travelXperience">TravelXperience</Link>
            <Link href="/brewingTips">Community</Link>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
