import { Dela_Gothic_One } from 'next/font/google';
import Link from 'next/link';
import styles from './globals.scss';

const inter = Dela_Gothic_One({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: {
    default: 'Home page | Roam the Globe',
    template: '%s | Roam the Globe',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <nav className={styles.navbar}>
            <h2 className={styles.logo}>Roam the Globe</h2>
            <ul className={styles.links}>
              <li className={styles.nailing}>
                <Link href="/">Home</Link>
              </li>
              <li className={styles.nailing}>
                <Link href="/travel-bundle">Travel bundles</Link>
              </li>
              <li className={styles.nailing}>
                <Link href="/travel-xperience">TravelXperience</Link>
              </li>
              <li className={styles.nailing}>
                <Link href="/cart">Cart</Link>
              </li>
            </ul>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
