import './globals.scss';
import { Dela_Gothic_One } from 'next/font/google';
import Link from 'next/link';

const inter = Dela_Gothic_One({ subsets: ['latin'], weight: '400' });

export const metadata = {
  title: {
    default: 'Home page | Roam the Globe',
    template: '%s | Roam the Globe',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/travel-bundle">Travel bundles</Link>
            <Link href="/travel-xperience">TravelXperience</Link>
            <Link href="/community">Community</Link>
          </nav>
        </div>

        {children}
      </body>
    </html>
  );
}
